
{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "jellyfin.fullname" . }}-media
  labels:
    app.kubernetes.io/name: {{ include "jellyfin.name" . }}
    helm.sh/chart: {{ include "jellyfin.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  volumeName: jellyfin-pv-nfs-media
  accessModes:
    - {{ .Values.persistence.media.accessMode | quote }}
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: {{ .Values.persistence.media.size | quote }}
{{- if .Values.persistence.media.storageClass }}
{{- if (eq "-" .Values.persistence.media.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.media.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-nfs-media
  namespace: jellyfin
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.persistence.media.size | quote }}  # < max. size we reserve for the pv. A bigger value than the configdata
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/test/jellyfin/media
    server: 192.168.203.15
    readOnly: false