apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "jellyfin.fullname" . }}-media
  labels:
    app.kubernetes.io/name: {{ include "jellyfin.name" . }}
    helm.sh/chart: {{ include "jellyfin.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.media.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size | quote }}
  selector:
    matchLabels:
      name: jellyfin-nfs-vol
      type: nfs