apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-nfs
  labels:
    type: nfs
    name: jellyfin-nfs-vol
spec:
  capacity:
    storage: {{ .Values.persistence.media.size | quote }}
  accessModes:
    - {{ .Values.persistence.media.accessMode | quote }}
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/test/jellyfin/media
    server: 192.168.37.105
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-nfs
  labels:
    app.kubernetes.io/name: {{ include "jellyfin.name" . }}
    helm.sh/chart: {{ include "jellyfin.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.media.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size | quote }}
  selector:
    matchLabels:
      type: nfs
      name: jellyfin-nfs-vol
