apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-nfs-config   # < name of the persisant volume ("pv") in kubenetes
  namespace: jellyfin            # < namespace where place the pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi                   # < max. size we reserve for the pv
  accessModes:
    - ReadWriteMany                # < Multiple pods can write to storage 
  persistentVolumeReclaimPolicy: Retain # < The persistent volume can reclaimed 
  nfs:
    path: "/mnt/test/sa2-25-23/Uladzislau_Krejzo/jellyfin/config"       # < Name of your NFS share with subfolder
    server: 192.168.37.105        # < IP number of your NFS server
    readOnly: false
    vers: 3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-nfs-data
  namespace: jellyfin
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi                   # < max. size we reserve for the pv. A bigger value than the configdata
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/mnt/test/sa2-25-23/Uladzislau_Krejzo/jellyfin/data"
    vers: 3            
    server: 192.168.37.105
    readOnly: false